#include <EtherCard.h>

void InserirGraficos()
{
    char *page = PSTR(

      "<div class='panel panel-default'>\r\n"
                      "<div class='panel-heading'><h4>Rede 1</h4></div>\r\n"
                      "<div class='panel-body'>\r\n"
"<div style='overflow-x:scroll'>\r\n"
"<div style='width: 1000px; height: 200px' id='cc1'></div>\r\n"
"<div style='width: 1000px; height: 200px' id='cc2'></div>\r\n"
"</div>\r\n"

                      "</div>\r\n"
                      "</div>\r\n"

      "<div class='panel panel-default'>\r\n"
                      "<div class='panel-heading'>Rede 2</div>\r\n"
                      "<div class='panel-body'>\r\n"
"<div style='overflow-x:scroll'>\r\n"
"<div style='width: 1000px; height: 200px' id='cc3'></div>\r\n"
"<div style='width: 1000px; height: 200px' id='cc4'></div>\r\n"
"</div>\r\n"

                      "</div>\r\n"
                      "</div>\r\n"

      "<div class='panel panel-default'>\r\n"
                      "<div class='panel-heading'>Rede 3</div>\r\n"
                      "<div class='panel-body'>\r\n"
"<div style='overflow-x:scroll'>\r\n"
"<div style='width: 1000px; height: 200px' id='cc5'></div>\r\n"
"<div style='width: 1000px; height: 200px' id='cc6'></div>\r\n"
"</div>\r\n"

                      "</div>\r\n"
                      "</div>\r\n"

      "<div class='panel panel-default'>\r\n"
                      "<div class='panel-heading'>Rede 4</div>\r\n"
                      "<div class='panel-body'>\r\n"
"<div style='overflow-x:scroll'>\r\n"
"<div style='width: 1000px; height: 200px' id='cc7'></div>\r\n"
"<div style='width: 1000px; height: 200px' id='cc8'></div>\r\n"
"</div>\r\n"

                      "</div>\r\n"
                      "</div>\r\n"


"<script>\r\n"
"RGraph.SVG.AJAX.getJSON('gdgraph1.js', function (json)\r\n"
"{\r\n"
"colors = ['#00B9F2'];\r\n"
"RGraph.SVG.GLOBALS.textSize = 5;\r\n"
"RGraph.SVG.GLOBALS.yaxisLabelsCount = 4;\r\n"
"RGraph.SVG.GLOBALS.textColor = 'gray';\r\n"
"RGraph.SVG.GLOBALS.gutterTop = 50;\r\n"
"RGraph.SVG.GLOBALS.gutterRight = 5;\r\n"
"RGraph.SVG.GLOBALS.backgroundGridBorder = false;\r\n"
"RGraph.SVG.GLOBALS.backgroundGridVlines = false;\r\n"
"RGraph.SVG.GLOBALS.xaxisTickmarks = false;\r\n"
"RGraph.SVG.GLOBALS.yaxis = false;\r\n"
"RGraph.SVG.GLOBALS.labelsAboveSize = 8;\r\n"
"RGraph.SVG.GLOBALS.labelsAbove = true;\r\n"
"RGraph.SVG.GLOBALS.xaxis = true;\r\n"
//"RGraph.SVG.GLOBALS.yaxisMax = 30;\r\n"
"RGraph.SVG.GLOBALS.colorsSequential = true;\r\n"

"new RGraph.SVG.Bar({\r\n"
"id: 'cc1',\r\n"
"data: json.ping0,\r\n"
"options: {\r\n"
"colors: json.cor0,\r\n"
"xaxisLabels: json.data0,\r\n"
"title: 'Ping'\r\n"
"}\r\n"
"}).wave();\r\n"

"new RGraph.SVG.Line({\r\n"
"id: 'cc2',\r\n"
"data: json.latencia0,\r\n"
"options: {\r\n"
"xaxisLabels: json.data0,\r\n"
"title: 'Latencia',\r\n"
"colors: ['red'],\r\n"
"spline: true,\r\n"
"filled: true,\r\n"
"filledColors: ['Gradient(rgba(255,0,0,0.75):rgba(255,0,0,0.5):rgba(255,0,0,0))']\r\n"
"}\r\n"
"}).trace();\r\n"

"new RGraph.SVG.Bar({\r\n"
"id: 'cc3',\r\n"
"data: json.ping1,\r\n"
"options: {\r\n"
"colors: json.cor1,\r\n"
"xaxisLabels: json.data1,\r\n"
"title: 'Ping'\r\n"
"}\r\n"
"}).wave();\r\n"
"new RGraph.SVG.Line({\r\n"
"id: 'cc4',\r\n"
"data: json.latencia1,\r\n"
"options: {\r\n"
"xaxisLabels: json.data1,\r\n"
"title: 'Latencia',\r\n"
"colors: ['red'],\r\n"
"spline: true,\r\n"
"filled: true,\r\n"
"filledColors: ['Gradient(rgba(255,0,0,0.75):rgba(255,0,0,0.5):rgba(255,0,0,0))']\r\n"
"}\r\n"
"}).trace();\r\n"

"new RGraph.SVG.Bar({\r\n"
"id: 'cc5',\r\n"
"data: json.ping2,\r\n"
"options: {\r\n"
"colors: json.cor2,\r\n"
"xaxisLabels: json.data2,\r\n"
"title: 'Ping'\r\n"
"}\r\n"
"}).wave();\r\n"
"new RGraph.SVG.Line({\r\n"
"id: 'cc6',\r\n"
"data: json.latencia2,\r\n"
"options: {\r\n"
"xaxisLabels: json.data2,\r\n"
"title: 'Latencia',\r\n"
"colors: ['red'],\r\n"
"spline: true,\r\n"
"filled: true,\r\n"
"filledColors: ['Gradient(rgba(255,0,0,0.75):rgba(255,0,0,0.5):rgba(255,0,0,0))']\r\n"
"}\r\n"
"}).trace();\r\n"

"new RGraph.SVG.Bar({\r\n"
"id: 'cc7',\r\n"
"data: json.ping3,\r\n"
"options: {\r\n"
"colors: json.cor3,\r\n"
"xaxisLabels: json.data3,\r\n"
"title: 'Ping'\r\n"
"}\r\n"
"}).wave();\r\n"
"new RGraph.SVG.Line({\r\n"
"id: 'cc8',\r\n"
"data: json.latencia3,\r\n"
"options: {\r\n"
"xaxisLabels: json.data3,\r\n"
"title: 'Latencia',\r\n"
"colors: ['red'],\r\n"
"spline: true,\r\n"
"filled: true,\r\n"
"filledColors: ['Gradient(rgba(255,0,0,0.75):rgba(255,0,0,0.5):rgba(255,0,0,0))']\r\n"
"}\r\n"
"}).trace();\r\n"
"});\r\n"
"</script>\r\n"

    );
    ether.fillAndSend(page, sizeof page);
}